### ISSUE TITLE
Please make read more link CSS selectable for styling

### ISSUE THREAD

**Issue by kristianmandrup** [jsantell/poet#105]
``` javascript
function readMoreLink (post) {
  var anchor = '<a href="' + post.url + '"';
  anchor += ' title="Read more of ' + post.title + '">read more</a>';
  return '<p class="read-more">' + anchor + '</p>';
}
```

Now I can center it if I like :)

``` css
p.read-more {
    text-align: center;
}
```
